imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

# Faker Configuration
bazinga_faker:
    locale: en_GB
    entities:
        Heri\TicketBundle\Model\Message:
            number: 30
            custom_formatters:
                Status:        { method: null }
                Source:        { method: null }
        Heri\TicketBundle\Model\User:
            number: 5
            custom_formatters:
                Fullname:      { method: name }
                Salt:          { method: md5 }
                LastLogin:     { method: dateTimeThisMonth }
                ExpireAt:      { method: null }
        Heri\TicketBundle\Model\Response:
            number: 30
            custom_formatters:
                IpAddress:     { method: ipv4 }